# backend/alembic/script.py.mako
"""initial schema

Revision ID: 5ce6e27cb53b
Revises: 434b95ad296f
Create Date: 2026-07-01 11:21:11.069556+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = "5ce6e27cb53b"
down_revision = "434b95ad296f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_messages_match_created", "messages", ["match_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_is_read"), "messages", ["is_read"], unique=False)
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.add_column("swipes", sa.Column("match_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, "swipes", "matches", ["match_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "swipes", type_="foreignkey")
    op.drop_column("swipes", "match_id")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_is_read"), table_name="messages")
    op.drop_index("idx_messages_match_created", table_name="messages")
    # ### end Alembic commands ###
