# backend/alembic/script.py.mako
"""add project_messages table

Revision ID: 223e184a64d8
Revises: 5ce6e27cb53b
Create Date: 2026-07-01 15:30:54.862781+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = "223e184a64d8"
down_revision = "5ce6e27cb53b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("LENGTH(content) <= 4000", name="chk_project_message_content_length"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_messages_project_created",
        "project_messages",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_messages_project_id"), "project_messages", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_messages_sender_id"), "project_messages", ["sender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_messages_sender_id"), table_name="project_messages")
    op.drop_index(op.f("ix_project_messages_project_id"), table_name="project_messages")
    op.drop_index("idx_project_messages_project_created", table_name="project_messages")
    op.drop_table("project_messages")
    # ### end Alembic commands ###
